"""empty message

Revision ID: dc01c54d367c
Revises: 
Create Date: 2021-12-03 16:31:00.347821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc01c54d367c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.Column('key_1', sa.String(length=256), nullable=True),
    sa.Column('key_2', sa.String(length=256), nullable=True),
    sa.Column('key_3', sa.String(length=256), nullable=True),
    sa.Column('key_4', sa.String(length=256), nullable=True),
    sa.Column('key_5', sa.String(length=256), nullable=True),
    sa.Column('key_6', sa.String(length=256), nullable=True),
    sa.Column('key_7', sa.String(length=256), nullable=True),
    sa.Column('key_8', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_pokemon_id'), 'property', ['pokemon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_pokemon_id'), table_name='property')
    op.drop_table('property')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
